
import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hubii
 */
public class OknoProgramu extends javax.swing.JFrame {

    Stan stan;

    public OknoProgramu() {

        initComponents();
        jPanel2.setVisible(false);
        jPanel7.setVisible(false);
        jPanel1.setVisible(false);
        

        stan = new Stan();
        wczytajDane();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        wysOsob = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        wysTemp = new javax.swing.JLabel();
        wysGlowneDrzwi = new javax.swing.JLabel();
        wysTylneDrzwi = new javax.swing.JLabel();
        wysGaraz = new javax.swing.JLabel();
        wysZuzycieEnergii = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        wysOgrzewanie = new javax.swing.JLabel();
        wysKlimatyzacja = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        wysZewnetrzne = new javax.swing.JLabel();
        wysKuchnia = new javax.swing.JLabel();
        wysKorytarz = new javax.swing.JLabel();
        wysPokojDziecka = new javax.swing.JLabel();
        wysSypialnia = new javax.swing.JLabel();
        wysSalon = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        zadanaTemp = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 618));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 618));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setMinimumSize(new java.awt.Dimension(520, 344));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 55));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ILOSC OSOB W BUDYNKU:");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        wysOsob.setBackground(new java.awt.Color(255, 255, 255));
        wysOsob.setForeground(new java.awt.Color(255, 255, 255));
        wysOsob.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wysOsob.setText("jLabel2");
        jPanel5.add(wysOsob, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TEMPERATURA POWIETRZA:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GŁÓWNE DRZWI:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TYLNE DRZWI:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 139, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GARAŻ:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ZUŻYCIE ENERGII :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 293, 250, -1));

        wysTemp.setForeground(new java.awt.Color(255, 255, 255));
        wysTemp.setText("jLabel2");
        jPanel5.add(wysTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        wysGlowneDrzwi.setForeground(new java.awt.Color(255, 255, 255));
        wysGlowneDrzwi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wysGlowneDrzwi.setText("jLabel2");
        jPanel5.add(wysGlowneDrzwi, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 120, 110, -1));

        wysTylneDrzwi.setForeground(new java.awt.Color(255, 255, 255));
        wysTylneDrzwi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wysTylneDrzwi.setText("jLabel2");
        jPanel5.add(wysTylneDrzwi, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 140, 110, -1));

        wysGaraz.setForeground(new java.awt.Color(255, 255, 255));
        wysGaraz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wysGaraz.setText("jLabel2");
        jPanel5.add(wysGaraz, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 160, 100, -1));

        wysZuzycieEnergii.setMaximum(77);
        jPanel5.add(wysZuzycieEnergii, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 314, 250, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 70, 70));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ZASILANIE");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 10, 210, 36));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OGRZEWANIE :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KLIMATYZACJA :");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("REGULACJA TEMPERATURY");

        wysOgrzewanie.setForeground(new java.awt.Color(255, 255, 255));
        wysOgrzewanie.setText("jLabel2");

        wysKlimatyzacja.setForeground(new java.awt.Color(255, 255, 255));
        wysKlimatyzacja.setText("jLabel2");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("OŚWIETLENIE");

        wysZewnetrzne.setForeground(new java.awt.Color(255, 255, 255));
        wysZewnetrzne.setText("ZEWNĘTRZNE");

        wysKuchnia.setForeground(new java.awt.Color(255, 255, 255));
        wysKuchnia.setText("KUCHNIA");

        wysKorytarz.setForeground(new java.awt.Color(255, 255, 255));
        wysKorytarz.setText("KORYTARZ");

        wysPokojDziecka.setForeground(new java.awt.Color(255, 255, 255));
        wysPokojDziecka.setText("POKOJ DZIECKA");

        wysSypialnia.setForeground(new java.awt.Color(255, 255, 255));
        wysSypialnia.setText("SYPIALNIA");

        wysSalon.setForeground(new java.awt.Color(255, 255, 255));
        wysSalon.setText("SALON");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysKlimatyzacja))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysOgrzewanie))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(wysKorytarz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysSalon))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(wysZewnetrzne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysPokojDziecka))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(wysKuchnia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysSypialnia)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(wysOgrzewanie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(wysKlimatyzacja))
                .addGap(61, 61, 61)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wysZewnetrzne)
                    .addComponent(wysPokojDziecka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wysKuchnia)
                    .addComponent(wysSypialnia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wysKorytarz)
                    .addComponent(wysSalon))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 60, 210, -1));

        jPanel6.setBackground(new java.awt.Color(200, 200, 200));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton5.setText("KUCHNIA");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, 93, -1));

        jToggleButton6.setText("ZEWĘTRZNE");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 93, 40));

        jToggleButton7.setText("KORYTARZ");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 194, 93, -1));

        jToggleButton8.setText("<HTML>POKÓJ<BR>DZIECKA");
        jToggleButton8.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton8.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 93, -1));

        jToggleButton9.setText("SYPIALNIA");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 164, 93, -1));

        jToggleButton10.setText("SALON");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 194, 93, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("<html>PANEL KONTROLNY<br> OŚWIETLENIA</html>");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 197, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("<html>Zdalna kontrola nad<br> oświetleniem w budynku.");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, 197, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 12, 220, 230));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        zadanaTemp.setModel(new javax.swing.SpinnerNumberModel(22, 15, 30, 1));

        jButton4.setText("Ustaw");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("<html>PANEL KONTROLNY<br> OGRZEWANIA I KLIMATYZACJI</html>");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("<html>Wprowadź żądaną temperature a<br> program zajmie się wszystkim!");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("℃");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(zadanaTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton4))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zadanaTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 12, 290, 230));

        jButton1.setText("odswież");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jButton3.setText("jButton3");
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 21, -1, -1));

        jToggleButton1.setText("ZASILANIE");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 12, 106, 43));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 20, 1));
        jPanel6.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 54, 29));

        jButton2.setText("Ustaw");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        jToggleButton2.setText("GARAŻ");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jToggleButton3.setText("GŁÓWNE DRZWI");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jToggleButton4.setText("TYLNE DRZWI");
        jPanel6.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jPanel2.isVisible()) {
            jPanel2.setVisible(false);
            jPanel7.setVisible(false);
            jPanel1.setVisible(false);
            jLabel2.setForeground(new java.awt.Color(70, 70, 70));
        } else {
            jPanel2.setVisible(true);
            jPanel7.setVisible(true);
            jPanel1.setVisible(true);
            jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        wczytajDane();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        stan.ustawTemp((Integer)zadanaTemp.getValue());
        wczytajDane();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        stan.toggleSwiatlo(4);
        wczytajDane();
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        stan.toggleSwiatlo(5);
        wczytajDane();
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        stan.toggleSwiatlo(3);
        wczytajDane();
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        stan.toggleSwiatlo(2);
        wczytajDane();
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        stan.toggleSwiatlo(1);
        wczytajDane();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        stan.toggleSwiatlo(0);
        wczytajDane();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoProgramu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel wysGaraz;
    private javax.swing.JLabel wysGlowneDrzwi;
    private javax.swing.JLabel wysKlimatyzacja;
    private javax.swing.JLabel wysKorytarz;
    private javax.swing.JLabel wysKuchnia;
    private javax.swing.JLabel wysOgrzewanie;
    private javax.swing.JLabel wysOsob;
    private javax.swing.JLabel wysPokojDziecka;
    private javax.swing.JLabel wysSalon;
    private javax.swing.JLabel wysSypialnia;
    private javax.swing.JLabel wysTemp;
    private javax.swing.JLabel wysTylneDrzwi;
    private javax.swing.JLabel wysZewnetrzne;
    private javax.swing.JProgressBar wysZuzycieEnergii;
    private javax.swing.JSpinner zadanaTemp;
    // End of variables declaration//GEN-END:variables

    public void wczytajDane() {
        //funkcja wczytuje dane do Labeli. Cała konwersja dokonywana jest tutaj.

        wysOsob.setText(Integer.toString(stan.iloscOsobWBudynku));
        wysTemp.setText(Integer.toString(stan.tempPowietrza) + "℃");

        //Drzwi główne
        if (stan.stDrzwi) {
            wysGlowneDrzwi.setText("OTWARTE");
            wysGlowneDrzwi.setForeground(Color.green);
        } else {
            wysGlowneDrzwi.setText("ZAMKNIĘTE");
            wysGlowneDrzwi.setForeground(Color.red);
        }
        //

        //Drzwi tylnie
        if (stan.stTylnichDrzwi) {
            wysTylneDrzwi.setText("OTWARTE");
            wysTylneDrzwi.setForeground(Color.green);
        } else {
            wysTylneDrzwi.setText("ZAMKNIĘTE");
            wysTylneDrzwi.setForeground(Color.red);
        }
        //

        //Garaż
        if (stan.stGaraz) {
            wysGaraz.setText("OTWARTE");
            wysGaraz.setForeground(Color.green);
        } else {
            wysGaraz.setText("ZAMKNIĘTE");
            wysGaraz.setForeground(Color.red);
        }

//////////////////////////////////////
        //Zuzycie energii
        wysZuzycieEnergii.setValue(stan.zuzycieEnergi);
        //
        
        
        //
///////////////////////////////////////
        //Temperatura
        if(stan.stOgrzewanie){
            wysOgrzewanie.setText("WŁĄCZONE");
            wysOgrzewanie.setForeground(new java.awt.Color(255, 150, 0));
        }
        else{
            wysOgrzewanie.setText("WYŁĄCZONE");
            wysOgrzewanie.setForeground(new java.awt.Color(50, 50, 50));
        }
        
        if(stan.stKlimatyzacja){
            wysKlimatyzacja.setText("WŁĄCZONE");
            wysKlimatyzacja.setForeground(new java.awt.Color(0, 200, 255));
        }
        else{
            wysKlimatyzacja.setText("WYŁĄCZONE");
            wysKlimatyzacja.setForeground(new java.awt.Color(50, 50, 50));
        }

///////////////////////////////////////
        //Swiatła
        if (stan.stSwiatlo[0]) {
            wysZewnetrzne.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysZewnetrzne.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[1]) {
            wysKuchnia.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysKuchnia.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[2]) {
            wysKorytarz.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysKorytarz.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[3]) {
            wysPokojDziecka.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysPokojDziecka.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[4]) {
            wysSypialnia.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysSypialnia.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[5]) {
            wysSalon.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysSalon.setForeground(new java.awt.Color(50, 50, 50));
        }
        //
        //////////////////////////////

    }
}
