package ZarzadzanieBudynkiem;


import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hubii
 */
public class OknoProgramu extends javax.swing.JFrame {

    Stan stan;

    public OknoProgramu() {

        initComponents();

        stan = new Stan();
        if (!stan.stZasilanie) {
            jPanel2.setVisible(false);
            jPanel7.setVisible(false);
            jPanel1.setVisible(false);
        }
        wczytajDane();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        wysOsob = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        wysTemp = new javax.swing.JLabel();
        wysGlowneDrzwi = new javax.swing.JLabel();
        wysTylneDrzwi = new javax.swing.JLabel();
        wysGaraz = new javax.swing.JLabel();
        wysZuzycieEnergii = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        wysOgrzewanie = new javax.swing.JLabel();
        wysKlimatyzacja = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        wysZewnetrzne = new javax.swing.JLabel();
        wysKuchnia = new javax.swing.JLabel();
        wysKorytarz = new javax.swing.JLabel();
        wysPokojDziecka = new javax.swing.JLabel();
        wysSypialnia = new javax.swing.JLabel();
        wysSalon = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jToggleKuchnia = new javax.swing.JToggleButton();
        jToggleZewnatrz = new javax.swing.JToggleButton();
        jToggleKorytarz = new javax.swing.JToggleButton();
        jTogglePokojDziecka = new javax.swing.JToggleButton();
        jToggleSypialnia = new javax.swing.JToggleButton();
        jToggleSalon = new javax.swing.JToggleButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        zadanaTemp = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleZasilanie = new javax.swing.JToggleButton();
        zadaneIloscOsob = new javax.swing.JSpinner();
        jButtonUstawIloscOsob = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jToggleGaraz = new javax.swing.JToggleButton();
        jToggleGlowneDrzwi = new javax.swing.JToggleButton();
        jToggleTylneDrzwi = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zazadzanie budynkiem");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 618));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setMinimumSize(new java.awt.Dimension(520, 344));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 55));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setLabelFor(jLabel1);
        jLabel1.setText("ILOSC OSOB W BUDYNKU:");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        wysOsob.setBackground(new java.awt.Color(255, 255, 255));
        wysOsob.setForeground(new java.awt.Color(255, 255, 255));
        wysOsob.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wysOsob.setText("jLabel2");
        wysOsob.setToolTipText("");
        jPanel5.add(wysOsob, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 60, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TEMPERATURA POWIETRZA:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GŁÓWNE DRZWI:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TYLNE DRZWI:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 139, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GARAŻ:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ZUŻYCIE ENERGII :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 293, 250, -1));

        wysTemp.setForeground(new java.awt.Color(255, 255, 255));
        wysTemp.setText("jLabel2");
        jPanel5.add(wysTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        wysGlowneDrzwi.setForeground(new java.awt.Color(255, 255, 255));
        wysGlowneDrzwi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wysGlowneDrzwi.setText("jLabel2");
        jPanel5.add(wysGlowneDrzwi, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 120, 110, -1));

        wysTylneDrzwi.setForeground(new java.awt.Color(255, 255, 255));
        wysTylneDrzwi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wysTylneDrzwi.setText("jLabel2");
        jPanel5.add(wysTylneDrzwi, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 140, 110, -1));

        wysGaraz.setForeground(new java.awt.Color(255, 255, 255));
        wysGaraz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wysGaraz.setText("jLabel2");
        jPanel5.add(wysGaraz, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 160, 100, -1));

        wysZuzycieEnergii.setMaximum(77);
        jPanel5.add(wysZuzycieEnergii, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 314, 250, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ZASILANIE");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 10, 210, 36));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OGRZEWANIE :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KLIMATYZACJA :");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("REGULACJA TEMPERATURY");

        wysOgrzewanie.setForeground(new java.awt.Color(255, 255, 255));
        wysOgrzewanie.setText("jLabel2");

        wysKlimatyzacja.setForeground(new java.awt.Color(255, 255, 255));
        wysKlimatyzacja.setText("jLabel2");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("OŚWIETLENIE");

        wysZewnetrzne.setForeground(new java.awt.Color(255, 255, 255));
        wysZewnetrzne.setText("ZEWNĘTRZNE");

        wysKuchnia.setForeground(new java.awt.Color(255, 255, 255));
        wysKuchnia.setText("KUCHNIA");

        wysKorytarz.setForeground(new java.awt.Color(255, 255, 255));
        wysKorytarz.setText("KORYTARZ");

        wysPokojDziecka.setForeground(new java.awt.Color(255, 255, 255));
        wysPokojDziecka.setText("POKOJ DZIECKA");

        wysSypialnia.setForeground(new java.awt.Color(255, 255, 255));
        wysSypialnia.setText("SYPIALNIA");

        wysSalon.setForeground(new java.awt.Color(255, 255, 255));
        wysSalon.setText("SALON");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysKlimatyzacja))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysOgrzewanie))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(wysKorytarz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysSalon))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(wysZewnetrzne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysPokojDziecka))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(wysKuchnia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wysSypialnia)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(wysOgrzewanie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(wysKlimatyzacja))
                .addGap(61, 61, 61)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wysZewnetrzne)
                    .addComponent(wysPokojDziecka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wysKuchnia)
                    .addComponent(wysSypialnia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wysKorytarz)
                    .addComponent(wysSalon))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 60, 210, -1));

        jPanel6.setBackground(new java.awt.Color(200, 200, 200));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleKuchnia.setText("KUCHNIA");
        jToggleKuchnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleKuchniaActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleKuchnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, 93, -1));

        jToggleZewnatrz.setText("ZEWĘTRZNE");
        jToggleZewnatrz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleZewnatrzActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleZewnatrz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 93, 40));

        jToggleKorytarz.setText("KORYTARZ");
        jToggleKorytarz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleKorytarzActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleKorytarz, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 194, 93, -1));

        jTogglePokojDziecka.setText("<HTML>POKÓJ<BR>DZIECKA");
        jTogglePokojDziecka.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTogglePokojDziecka.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTogglePokojDziecka.setMargin(new java.awt.Insets(2, 3, 2, 3));
        jTogglePokojDziecka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTogglePokojDzieckaActionPerformed(evt);
            }
        });
        jPanel7.add(jTogglePokojDziecka, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 93, -1));

        jToggleSypialnia.setText("SYPIALNIA");
        jToggleSypialnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleSypialniaActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleSypialnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 164, 93, -1));

        jToggleSalon.setText("SALON");
        jToggleSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleSalonActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 194, 93, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("<html>PANEL KONTROLNY<br> OŚWIETLENIA</html>");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 197, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("<html>Zdalna kontrola nad<br> oświetleniem w budynku.");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, 197, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 12, 220, 230));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        zadanaTemp.setModel(new javax.swing.SpinnerNumberModel(22, 15, 30, 1));

        jButton4.setText("Ustaw");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("<html>PANEL KONTROLNY<br> OGRZEWANIA I KLIMATYZACJI</html>");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("<html>Wprowadź żądaną temperature a<br> program zajmie się wszystkim!");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("℃");

        jButton6.setText("Wyłącz");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(zadanaTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zadanaTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 12, 290, 230));

        jButton1.setText("odswież");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 21, -1, -1));

        jToggleZasilanie.setText("ZASILANIE");
        jToggleZasilanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleZasilanieActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleZasilanie, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 12, 106, 43));

        zadaneIloscOsob.setModel(new javax.swing.SpinnerNumberModel(1, 0, 20, 1));
        jPanel6.add(zadaneIloscOsob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 54, 29));

        jButtonUstawIloscOsob.setText("Ustaw");
        jButtonUstawIloscOsob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUstawIloscOsobActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonUstawIloscOsob, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        jToggleGaraz.setText("GARAŻ");
        jToggleGaraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleGarazActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleGaraz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jToggleGlowneDrzwi.setText("GŁÓWNE DRZWI");
        jToggleGlowneDrzwi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleGlowneDrzwiActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleGlowneDrzwi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jToggleTylneDrzwi.setText("TYLNE DRZWI");
        jToggleTylneDrzwi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleTylneDrzwiActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleTylneDrzwi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUstawIloscOsobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUstawIloscOsobActionPerformed
        stan.iloscOsobWBudynku = (Integer) zadaneIloscOsob.getValue();
        wczytajDane();
    }//GEN-LAST:event_jButtonUstawIloscOsobActionPerformed

    private void jToggleZasilanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleZasilanieActionPerformed
        if (jPanel2.isVisible()) {
            wylaczWszystkoZZasilania();
            jPanel2.setVisible(false);
            jPanel7.setVisible(false);
            jPanel1.setVisible(false);

        } else {
            jPanel2.setVisible(true);
            jPanel7.setVisible(true);
            jPanel1.setVisible(true);

        }
        if (stan.stZasilanie) {
            stan.stZasilanie = false;
            stan.tempPowietrza=Stan.TEMP;
        } else {
            stan.stZasilanie = true;
        }
        wczytajDane();
        

    }//GEN-LAST:event_jToggleZasilanieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        wczytajDane();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleGlowneDrzwiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleGlowneDrzwiActionPerformed
        if (stan.stZasilanie) {
            stan.toggleDrzwi(1);
            wczytajDane();
        } else {
            if (jToggleGlowneDrzwi.isSelected()) {
                jToggleGlowneDrzwi.setSelected(false);
            } else {
                jToggleGlowneDrzwi.setSelected(true);
            }
            JOptionPane.showMessageDialog(this, "Włącz zasilanie.");

        }
    }//GEN-LAST:event_jToggleGlowneDrzwiActionPerformed

    private void jToggleGarazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleGarazActionPerformed
        if (stan.stZasilanie) {
            stan.toggleDrzwi(3);
            wczytajDane();
        } else {
            if (jToggleGaraz.isSelected()) {
                jToggleGaraz.setSelected(false);
            } else {
                jToggleGaraz.setSelected(true);
            }
            JOptionPane.showMessageDialog(this, "Włącz zasilanie.");

        }
    }//GEN-LAST:event_jToggleGarazActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        stan.ustawTemp((Integer) zadanaTemp.getValue());
        wczytajDane();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleSypialniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleSypialniaActionPerformed
        stan.toggleSwiatlo(4);
        wczytajDane();
    }//GEN-LAST:event_jToggleSypialniaActionPerformed

    private void jToggleSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleSalonActionPerformed
        stan.toggleSwiatlo(5);
        wczytajDane();
    }//GEN-LAST:event_jToggleSalonActionPerformed

    private void jTogglePokojDzieckaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTogglePokojDzieckaActionPerformed
        stan.toggleSwiatlo(3);
        wczytajDane();
    }//GEN-LAST:event_jTogglePokojDzieckaActionPerformed

    private void jToggleKorytarzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleKorytarzActionPerformed
        stan.toggleSwiatlo(2);
        wczytajDane();
    }//GEN-LAST:event_jToggleKorytarzActionPerformed

    private void jToggleKuchniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleKuchniaActionPerformed
        stan.toggleSwiatlo(1);
        wczytajDane();
    }//GEN-LAST:event_jToggleKuchniaActionPerformed

    private void jToggleZewnatrzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleZewnatrzActionPerformed
        stan.toggleSwiatlo(0);
        wczytajDane();
    }//GEN-LAST:event_jToggleZewnatrzActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.out.println(jToggleZewnatrz.isSelected());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        stan.ustawTemp(stan.TEMP);
        zadanaTemp.setValue(stan.TEMP);
        wczytajDane();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jToggleTylneDrzwiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleTylneDrzwiActionPerformed
        if (stan.stZasilanie) {
            stan.toggleDrzwi(2);
            wczytajDane();
        } else {
            if (jToggleTylneDrzwi.isSelected()) {
                jToggleTylneDrzwi.setSelected(false);
            } else {
                jToggleTylneDrzwi.setSelected(true);
            }
            JOptionPane.showMessageDialog(this, "Włącz zasilanie.");

        }
    }//GEN-LAST:event_jToggleTylneDrzwiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        stan.zapiszStan();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonUstawIloscOsob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToggleButton jToggleGaraz;
    private javax.swing.JToggleButton jToggleGlowneDrzwi;
    private javax.swing.JToggleButton jToggleKorytarz;
    private javax.swing.JToggleButton jToggleKuchnia;
    private javax.swing.JToggleButton jTogglePokojDziecka;
    private javax.swing.JToggleButton jToggleSalon;
    private javax.swing.JToggleButton jToggleSypialnia;
    private javax.swing.JToggleButton jToggleTylneDrzwi;
    private javax.swing.JToggleButton jToggleZasilanie;
    private javax.swing.JToggleButton jToggleZewnatrz;
    private javax.swing.JLabel wysGaraz;
    private javax.swing.JLabel wysGlowneDrzwi;
    private javax.swing.JLabel wysKlimatyzacja;
    private javax.swing.JLabel wysKorytarz;
    private javax.swing.JLabel wysKuchnia;
    private javax.swing.JLabel wysOgrzewanie;
    private javax.swing.JLabel wysOsob;
    private javax.swing.JLabel wysPokojDziecka;
    private javax.swing.JLabel wysSalon;
    private javax.swing.JLabel wysSypialnia;
    private javax.swing.JLabel wysTemp;
    private javax.swing.JLabel wysTylneDrzwi;
    private javax.swing.JLabel wysZewnetrzne;
    private javax.swing.JProgressBar wysZuzycieEnergii;
    private javax.swing.JSpinner zadanaTemp;
    private javax.swing.JSpinner zadaneIloscOsob;
    // End of variables declaration//GEN-END:variables

    public void wczytajDane() {
        //funkcja wczytuje dane do Labeli. Cała konwersja dokonywana jest tutaj.

        wysOsob.setText(Integer.toString(stan.iloscOsobWBudynku));
        wysTemp.setText(Integer.toString(stan.tempPowietrza) + "℃");

        //Drzwi główne
        if (stan.stDrzwi) {
            wysGlowneDrzwi.setText("OTWARTE");
            wysGlowneDrzwi.setForeground(Color.green);
        } else {
            wysGlowneDrzwi.setText("ZAMKNIĘTE");
            wysGlowneDrzwi.setForeground(Color.red);
        }
        //

        //Drzwi tylnie
        if (stan.stTylnichDrzwi) {
            wysTylneDrzwi.setText("OTWARTE");
            wysTylneDrzwi.setForeground(Color.green);
        } else {
            wysTylneDrzwi.setText("ZAMKNIĘTE");
            wysTylneDrzwi.setForeground(Color.red);
        }
        //

        //Garaż
        if (stan.stGaraz) {
            wysGaraz.setText("OTWARTE");
            wysGaraz.setForeground(Color.green);
        } else {
            wysGaraz.setText("ZAMKNIĘTE");
            wysGaraz.setForeground(Color.red);
        }

//////////////////////////////////////
        //Zuzycie energii
        wysZuzycieEnergii.setValue(stan.zuzycieEnergi);
        //

        //
///////////////////////////////////////
        //Temperatura
        if (stan.stOgrzewanie) {
            wysOgrzewanie.setText("WŁĄCZONE");
            wysOgrzewanie.setForeground(new java.awt.Color(255, 150, 0));
        } else {
            wysOgrzewanie.setText("WYŁĄCZONE");
            wysOgrzewanie.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stKlimatyzacja) {
            wysKlimatyzacja.setText("WŁĄCZONE");
            wysKlimatyzacja.setForeground(new java.awt.Color(0, 200, 255));
        } else {
            wysKlimatyzacja.setText("WYŁĄCZONE");
            wysKlimatyzacja.setForeground(new java.awt.Color(50, 50, 50));
        }

///////////////////////////////////////
        //Swiatła
        if (stan.stSwiatlo[0]) {
            wysZewnetrzne.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysZewnetrzne.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[1]) {
            wysKuchnia.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysKuchnia.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[2]) {
            wysKorytarz.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysKorytarz.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[3]) {
            wysPokojDziecka.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysPokojDziecka.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[4]) {
            wysSypialnia.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysSypialnia.setForeground(new java.awt.Color(50, 50, 50));
        }

        if (stan.stSwiatlo[5]) {
            wysSalon.setForeground(new java.awt.Color(200, 200, 0));
        } else {
            wysSalon.setForeground(new java.awt.Color(50, 50, 50));
        }
        //
        //////////////////////////////
        // PRZYCISK ZASILANIA
        if (!stan.stZasilanie) {
            stan.tempPowietrza = Stan.TEMP;
            jLabel2.setForeground(new java.awt.Color(70, 70, 70));
        } else {
            jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        }
        //////////////////////
        nastawTogglesy();
    }

    private void wylaczWszystkoZZasilania() {

        stan.stKlimatyzacja = false;
        stan.stOgrzewanie = false;

        for (int i = 0; i < stan.stSwiatlo.length; i++) {
            if (stan.stSwiatlo[i]) {
                stan.toggleSwiatlo(i);
            }
        }

        jToggleKorytarz.setSelected(false);
        jToggleKuchnia.setSelected(false);
        jTogglePokojDziecka.setSelected(false);
        jToggleSalon.setSelected(false);
        jToggleSypialnia.setSelected(false);
        jToggleZewnatrz.setSelected(false);

        stan.zuzycieEnergi = 0;
        wczytajDane();

    }

    private void nastawTogglesy() {
        if (!stan.stDrzwi) {
            jToggleGlowneDrzwi.setSelected(true);
        }

        if (!stan.stTylnichDrzwi) {
            jToggleTylneDrzwi.setSelected(true);
        }
        if (!stan.stGaraz) {
            jToggleGaraz.setSelected(true);
        }
        //swiatla
        if(stan.stSwiatlo[0]){
            jToggleZewnatrz.setSelected(true);
        }
        if(stan.stSwiatlo[1]){
            jToggleKuchnia.setSelected(true);
        }
        if(stan.stSwiatlo[2]){
            jToggleKorytarz.setSelected(true);
        }
        if(stan.stSwiatlo[3]){
            jTogglePokojDziecka.setSelected(true);
        }
        if(stan.stSwiatlo[4]){
            jToggleSypialnia.setSelected(true);
        }
        if(stan.stSwiatlo[5]){
            jToggleSalon.setSelected(true);
        }
        //
    }
}
